version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ecto_sql
    versions:
    - 3.6.0
  - dependency-name: ex_machina
    versions:
    - 2.5.0
    - 2.6.0
  - dependency-name: excoveralls
    versions:
    - 0.13.4
  - dependency-name: credo
    versions:
    - 1.5.4
