language: elixir

elixir: 1.7.4

otp_release: 21.0.9

# Required for Postgresql 10
dist: xenial

services:
  - postgresql

addons:
  postgresql: 10

branches:
  only:
    - master

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

before_deploy:
  - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git

deploy:
  provider: script
  script: git push -f gigalixir HEAD:refs/heads/master
  on:
    branch: master
